### ISSUE TITLE
help with multiple collections in new 2.x version

### ISSUE THREAD

**Issue by sargac** [AbcAeffchen/Sephpa#28]
Hi,

I saw the multiple collections support is unfortunately removed from the new 2.x beta version. Our bank still supports this version, and I really need this functionality, so first of all, I would like to know, if there is an option, the old functionality to be added to new 2.x branch?

If not, I would like to know, if there is any way in the new version, to somehow still create multiple batch XML files, as in previous version, and if so, how would I do this? Could this be done with the new Multi File class and how?

Best,

**Comment by AbcAeffchen** [comment]
To the best of my knowledge, no bank supports multiple collections in one file even though the SEPA file specification explicitly allows it. But some banks do automatically/silently split up such files into multiple files.

Since the aim of Sephpa is to create valid files that will not be rejected by your bank I dropped the support for multiple collections in one file. However, you can just run your code in a loop an create more files.  

For an example of how SephpaMultiFile works you can have a look into [SephpaStoreTest.php](https://github.com/AbcAeffchen/Sephpa/blob/master/tests/SephpaStoreTests.php#L181)

Sorry for the missing documentation. I just couldn't find enough time to write the documentation and fully publish v2.0.

**Comment by sargac** [comment]
Thank you for your reply! I'll take a look at SephpaStoreTest.php file.

In Austria, Raiffeisen Bank fully supports batch XML files, which are even displayed as batch files after uploading them to bank in their Elba software. I was also in contact with their development team.

It is much easier to upload 1 batch file instead of 100 separate files for small payments, that why I'm trying to find a way to do that in a new version. If you can guide me in the right direction to generate one batch file in v2.0, that would be much appreciated.

I can help you with the documentation and testing, if you like, so you can fully publish v2.0.

**Comment by AbcAeffchen** [comment]
ok. This is new to me. at least a few years ago it was not supported by any german bank (as far as I know). At best they did the conversion on their own instead of giving you an error.

If I remember correctly I dropped the support for that. So I need to do a partial rollback. The cleanest solution would be to bring back the support for that and recommend not to use it.

Thanks for your offer. For 2.0 I plan to look into the latest changes in SEPA file format and if there is something Sephpa should support. I also need to update the CI process to work with PHP 7.1+ and maybe drop support for very old PHP versions as no should use them anyway. If you want to invest some time, writing the documentation would be very nice. I planned to move it from the readme file into a wiki, but never made it that far.

**Comment by sargac** [comment]
Thank you, a rollback would be much appreciated, and I am more than willing to invest my time writing the documentation, so I've sent you an email to further discuss the subject.

**Comment by Heart1010** [comment]
It's relevant how the generated xml file ist transported to the bank.
If the xml file will be sent over FinTS/HBCI multiple collections are not allowed!
But if you send it via EBICS for example or upload it over your banks eBanking Interface a multiple collection xml file is fine!

**Comment by sargac** [comment]
Thank you for your feedback, Heart1010. I'm uploading it over my eBanking interface, and the batch stays batch even after it's uploaded to a banking software. So I can see 1 record on my payments list, and I can drill down to it, to see the separate payments.

**Comment by AbcAeffchen** [comment]
Ah. Now it makes more sense to me. Thanks @Heart1010 .
