### ISSUE TITLE
Since Update addPayment function is lost

### ISSUE THREAD

**Issue by skipper2020** [AbcAeffchen/Sephpa#29]
Hello,
since the last Update  5 days ago the function of addPayment in the code of the direct debits is lost. 
It seems to be that the clean up of the code have been a bit to much.
Thanks to fix it.
Kind regards 
Timo

**Comment by AbcAeffchen** [comment]
Hi,
There was a interface simplification planned for version 2.0. But it turned out that this simplification removed functionality that is useful in some cases, so this part is rolled back again.

So addPayment is not lost but you have to make an extra step on creating a collection first. So it is
Create a file -> addCollection -> addPayment.
And you should probably only add one collection and add all payments to this collection if possible.

Sorry for the inconvenience. There will also be a wiki to document all the functionality of Sephpa much better. Hopefully it will be there in the next few weeks or even days.

Best
Alex
